baseURL = "https://francis5566.github.io/fw1993/"
theme = "beautifulhugo" # set the theme
publishDir = "docs"
languageCode = "en-us"
title = "fw1993"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "../post/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "../about/"