baseURL = "https://francis5566.github.io/fw1993/"
theme = "beautifulhugo" # set the theme
publishDir = "docs"
languageCode = "en-us"
title = "fw1993"
pygmentsUseClasses = true

[blackfriday]
[taxonomies]
   tag = "tags"
   category = "categories"

# Menu links
[[menu.main]]
    name = "Tags"
    weight = 1
    url  = "./tags/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url  = "./post/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "./about/"