baseurl = "https://goatwu1993.github.io/blog/"
title = "goatwu1993"
copyright = "Copyright &copy; 2019 - goatwu1993"
canonifyurls = true
theme = "hugo-academic"
themesDir = "themes"
publishDir = "docs"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Chao Yang Wu"
    github = "goatwu1993"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "A note of work & study problems"
